export const FEATURE_FLAG_MODULE_OPTIONS = Symbol('FEATURE_FLAG_MODULE_OPTIONS');

export const DEFAULT_CACHE_TTL_MS = 30_000;

export const FEATURE_FLAG_KEY = 'FEATURE_FLAG_KEY';
export const FEATURE_FLAG_OPTIONS_KEY = 'FEATURE_FLAG_OPTIONS_KEY';
export const BYPASS_FEATURE_FLAG_KEY = 'BYPASS_FEATURE_FLAG_KEY';

export const CACHE_ADAPTER = Symbol('CACHE_ADAPTER');
